[theme]
base = "light"
primaryColor = "#B3242E"
backgroundColor = "#F2F1ED"
secondaryBackgroundColor = "#E6E3DA"
textColor = "#1A1814"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
