[theme]
base = "light"
backgroundColor = "#F2F1ED"
primaryColor = "#B3242E"
secondaryBackgroundColor = "#E6E3DA"
font = "sans serif"
textColor = "#1A1814"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false